# Generated by Django 6.0.4 on 2026-04-25 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=20)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Gescol.classe')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('date_rendu', models.DateTimeField()),
                ('fichier_attache', models.FileField(blank=True, null=True, upload_to='devoirs/consignes/%Y/%m/')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='Gescol.cours')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-date_attribution'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='Gescol.classe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AutoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('comprehension_notion', models.IntegerField(choices=[(1, 'Très insuffisant'), (2, 'Insuffisant'), (3, 'Passable'), (4, 'Bien'), (5, 'Très bien')], default=3)),
                ('facilite_exercices', models.IntegerField(choices=[(1, 'Très insuffisant'), (2, 'Insuffisant'), (3, 'Passable'), (4, 'Bien'), (5, 'Très bien')], default=3)),
                ('interet_matiere', models.IntegerField(choices=[(1, 'Très insuffisant'), (2, 'Insuffisant'), (3, 'Passable'), (4, 'Bien'), (5, 'Très bien')], default=3)),
                ('points_difficultes', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluations', to='Gescol.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluations', to='Gescol.eleve')),
            ],
            options={
                'verbose_name': 'Auto-Évaluation',
                'verbose_name_plural': 'Auto-Évaluations',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='Gescol.matiere')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Gescol.enseignant'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_evaluation', models.CharField(choices=[('DEVOIR', 'Devoir'), ('INTERROGATION', 'Interrogation'), ('EXAMEN', 'Examen'), ('PROJET', 'Projet'), ('PARTICIPATION', 'Participation')], default='DEVOIR', max_length=20)),
                ('date_evaluation', models.DateField()),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Gescol.cours')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navigateur', models.CharField(blank=True, max_length=200)),
                ('succes', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_connexion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de Connexion',
                'verbose_name_plural': 'Journaux de Connexion',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Gescol.matiere'),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='Gescol.matiere')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['matiere', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Gescol.niveau'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appreciation', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='Gescol.competence')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Gescol.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Gescol.evaluation')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_saisie'],
                'unique_together': {('evaluation', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('devoir_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='Gescol.devoir')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('note_associee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='Gescol.note')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('DEVOIR', 'Nouveau devoir'), ('NOTE', 'Nouvelle note'), ('MESSAGE', 'Nouveau message'), ('COURS', 'Modification de cours'), ('RAPPEL', 'Rappel'), ('ALERTE', 'Alerte pédagogique')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('enfants', models.ManyToManyField(blank=True, related_name='parents', to='Gescol.eleve')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_item', models.CharField(choices=[('PROJET', 'Projet scolaire'), ('CERTIFICATION', 'Certification'), ('EXTRA_SCO', 'Accomplissement extra-scolaire'), ('AUTRE', 'Autre')], default='PROJET', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='portfolio/%Y/%m/')),
                ('lien_externe', models.URLField(blank=True)),
                ('date_realisation', models.DateField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='Gescol.eleve')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='RessourcePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_ressource', models.CharField(choices=[('COURS', 'Support de cours'), ('EXERCICE', 'Exercice'), ('CORRIGE', 'Corrigé'), ('DOCUMENT', 'Document général'), ('VIDEO', 'Vidéo'), ('LIEN', 'Lien externe')], default='COURS', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/%Y/%m/')),
                ('lien_externe', models.URLField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='Gescol.cours')),
            ],
            options={
                'verbose_name': 'Ressource Pédagogique',
                'verbose_name_plural': 'Ressources Pédagogiques',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='SuiviPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('NON_COMPRISE', 'Non comprise'), ('PARTIELLEMENT', 'Partiellement comprise'), ('COMPRISE', 'Comprise'), ('MAITRISEE', 'Maîtrisée')], default='NON_COMPRISE', max_length=20)),
                ('commentaire_eleve', models.TextField(blank=True)),
                ('commentaire_enseignant', models.TextField(blank=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('resolu', models.BooleanField(default=False)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='Gescol.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_pedagogique', to='Gescol.eleve')),
            ],
            options={
                'verbose_name': 'Suivi Pédagogique',
                'verbose_name_plural': 'Suivis Pédagogiques',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='DevoirSoumis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='devoirs/soumis/%Y/%m/')),
                ('commentaire_eleve', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('CORRIGE', 'Corrigé'), ('RETOURNE', 'Retourné pour modification')], default='SOUMIS', max_length=20)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commentaire_enseignant', models.TextField(blank=True)),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='Gescol.devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs_soumis', to='Gescol.eleve')),
            ],
            options={
                'verbose_name': 'Devoir Soumis',
                'verbose_name_plural': 'Devoirs Soumis',
                'ordering': ['-date_soumission'],
                'unique_together': {('devoir', 'eleve')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee_scolaire')},
        ),
    ]
