# Generated by Django 6.0.4 on 2026-05-01 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gescol', '0002_alter_journalconnexion_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='evaluations/soumissions/%Y/%m/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('CORRIGE', 'Corrigé')], default='SOUMIS', max_length=20)),
                ('commentaire_enseignant', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_soumises', to='Gescol.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='Gescol.evaluation')),
            ],
            options={
                'verbose_name': 'Soumission d’évaluation',
                'verbose_name_plural': 'Soumissions d’évaluations',
                'ordering': ['-date_soumission'],
                'unique_together': {('evaluation', 'eleve')},
            },
        ),
    ]
