# Generated by Codex on 2026-05-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gescol', '0004_evaluation_fichier_attache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('libelle', models.CharField(default='Frais académiques', max_length=150)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_academiques', to='Gescol.classe')),
            ],
            options={
                'verbose_name': 'Frais Académique',
                'verbose_name_plural': 'Frais Académiques',
                'ordering': ['classe__nom', '-annee_scolaire'],
                'unique_together': {('classe', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='PaiementFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('ACOMPTE', 'Acompte'), ('SOLDE', 'Solde')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_recu', models.CharField(blank=True, max_length=40, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_frais', to='Gescol.eleve')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_frais_enregistres', to=settings.AUTH_USER_MODEL)),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Gescol.fraisacademique')),
            ],
            options={
                'verbose_name': 'Paiement de Frais',
                'verbose_name_plural': 'Paiements de Frais',
                'ordering': ['-date_paiement'],
                'unique_together': {('eleve', 'frais', 'type_paiement')},
            },
        ),
    ]
