# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gescol', '0005_fraisacademique_paiementfrais'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfrais',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement bancaire'), ('CARTE', 'Carte bancaire')], default='ESPECES', max_length=20),
        ),
        migrations.AddField(
            model_name='paiementfrais',
            name='nom_payeur',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiementfrais',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiementfrais',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paiementfrais',
            name='telephone_payeur',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
